name: Api Mongoose V1

on: [push]
# cuándo se ejecutará el workflow

jobs:
  # Primero hace el build
  build:
    # El CI se ejecutará en ubuntu
    runs-on: ubuntu-latest
    # Los pasos para hacer build
    steps:
      # Qué versión de actions ocupará
      - uses: actions/checkout@v2
      # nombro el paso en el que estás
      - name: Build image Docker
      # Comando para hacer el build
      - run: docker build . --file Dockerfile --tag api-mongoose-v1

  # Luego hace el test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests API
      # Esto es para requerir node
        uses: actions/setup-node@v1
      - with:
        # probar esto con la versión 12 de node
        node-version: "12.x"
      - run: npm ci
      - run: npm test
